### ISSUE TITLE
Verify integrity of image registration

### ISSUE THREAD

**Issue by msteiger** [boothen/Json-Eclipse-Plugin#4]
This applies to version 0.9.8 and might be fixed already (migrated issue from sourceforge).

The image for each node is acquired and then leaked. Using the outline view with the Json editor will result in SWT running out of handles eventually. The JsonTreeNode's getImage method is where the problem occurs.

The real problem is that the map of types-to-image should really be using an `org.eclipse.jface.resource.ImageRegistry` and put the `ImageDescriptor` followed by getting the image from that.

``` java
ImageRegistry registry = new ImageRegistry();
registry.put(JsonArrayNode.class.getName(), 
    ImageDescriptor.createFromURL(JsonNode.getResource("/icons/JsonArray.gif")))
}

public Image getImage() {
    return registry.get(jsonNode.getClass().getName());
}
```

**Comment by alblue** [comment]
Looks like the approach changed and cached images were used:

https://github.com/boothen/Json-Eclipse-Plugin/blob/534bc0e5381097c77a7153c58cedfefe070b1946/jsonedit-outline/src/main/java/com/boothen/jsonedit/outline/JsonContextImageVisitor.java#L74

You might still find it advantageous to use an ImageRegistry and ImageDescriptors because this will then handle the caching for you and can replace the getCachedImage method you're using, but the underlying problem seems to be resolved.

**Comment by msteiger** [comment]
Yes, I agree. Thank you!
